import type { GanttTheme } from "@gantt-chart/core";
import { lightPalette } from "./palette";
import { defaultFont, defaultMetrics } from "./shared";

export const lightTheme: GanttTheme = {
  name: "light",
  dark: false,
  colors: {
    background: "#ffffff",
    rowEven: "#ffffff",
    rowOdd: "#f8fafc",
    rowHover: "#eef2ff",
    rowSelected: "#e0e7ff",
    border: "#d8dee9",
    gridLine: "#eceff4",
    gridLineStrong: "#d8dee9",
    text: "#222b3b",
    textMuted: "#64748b",
    textInverse: "#ffffff",
    accent: "#3b6fe0",
    taskFill: "#3b6fe0",
    taskStroke: "#2b53a8",
    taskText: "#ffffff",
    milestoneFill: "#1e293b",
    selectionFill: "#1d4ed8",
    selectionStroke: "#222b3b",
    hoverStroke: "#1e293b",
    dragGhost: "rgba(59, 111, 224, 0.35)",
    dragPreviewStroke: "#1d4ed8",
    marqueeFill: "rgba(59, 111, 224, 0.12)",
    marqueeStroke: "#3b6fe0",
    todayLine: "#dc2626",
    markerLine: "#7c3aed",
    dependencyLine: "#94a3b8",
    scrollbarThumb: "#c3ccd8",
    scrollbarTrack: "#f1f5f9",
  },
  metrics: { ...defaultMetrics },
  palette: lightPalette,
  font: { ...defaultFont },
};
